[supervisord]
nodaemon=false
user=root
pidfile=/run/supervisord-streaming.pid
logfile=/var/log/streaming/supervisord.log
childlogdir=/var/log/streaming

[unix_http_server]
file=/run/supervisor-streaming.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///run/supervisor-streaming.sock

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
priority=10
autostart=true
autorestart=true
startsecs=2
stdout_logfile=/var/log/streaming/nginx-supervisor.log
stderr_logfile=/var/log/streaming/nginx-supervisor-error.log

[program:hls-packager]
command=/usr/local/bin/package-hls
priority=20
autostart=true
autorestart=true
startsecs=5
startretries=1000
stopasgroup=true
killasgroup=true
stdout_logfile=/var/log/streaming/hls.log
redirect_stderr=true

[program:dash-packager]
command=/usr/local/bin/package-dash
priority=20
autostart=true
autorestart=true
startsecs=5
startretries=1000
stopasgroup=true
killasgroup=true
stdout_logfile=/var/log/streaming/dash.log
redirect_stderr=true
